ignore:
  - cmake/
  - gframe/
  - ikpmp3/
  - ocgcore/
  - premake/
  - appveyor.yml
  - premake4.lua
  - premake5.lua
  - CMakeLists.txt
  - update-koishipro/
path: ./koishipro
url: https://koishi.pro/ygopro/
